### ISSUE TITLE
Remove jest warning regarding update to SimpleImage

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2387]
**Is your feature request related to a problem? Please describe.**
Since we changed to the svg transformer the native images in our tests aren't mocked anymore. Therefore there are a bunch of errors although these errors probably don't have any impact on the result this should be fixed.

<details>
<summary>Stacktrace</summary>
  console.error
    Warning: An update to SimpleImage inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at SimpleImage (/Users/digitalfabrik/projects/integreat-app/native/src/components/SimpleImage.tsx:28:3)
        at StyledNativeComponent (/Users/digitalfabrik/projects/integreat-app/native/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
        at Styled(SimpleImage)
        at View
        at Component (/Users/digitalfabrik/projects/integreat-app/native/node_modules/react-native/jest/mockComponent.js:28:18)
        at StyledNativeComponent (/Users/digitalfabrik/projects/integreat-app/native/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
        at Styled(View)
        at PoiDetails (/Users/digitalfabrik/projects/integreat-app/native/src/components/PoiDetails.tsx:54:23)
        at useContext (/Users/digitalfabrik/projects/integreat-app/native/node_modules/styled-components/src/models/ThemeProvider.js:48:22)
        at wrapWithTheme (/Users/digitalfabrik/projects/integreat-app/native/src/testing/wrapWithTheme.tsx:6:26)
</details>

**Describe the solution you'd like**
Mock SimpleImage where the error occurs or wrap in act where needed. 

**Describe alternatives you've considered**
Mock svgs in tests. But I'm unsure whether this actually fixes the issue.

**Additional context**
N/A

**Comment by steffenkleinle** [comment]
I think we only use simpleimage for non-svgs? Not sure though. Possibly related to #1882 and #2378.

**Comment by sarahsporck** [comment]
Maybe. I'll take a look at this, as soon I've got some time on my hands. Don't like it if tests are 🔴red
